import type { Campaign, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@zendafund.com',
    role: 'admin',
    credits: 1000,
    profilePic: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: '2',
    name: 'Aisha Rahman',
    email: 'creator@zendafund.com',
    role: 'creator',
    credits: 250,
    profilePic: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
  },
  {
    id: '3',
    name: 'Nabil Hasan',
    email: 'supporter@zendafund.com',
    role: 'supporter',
    credits: 500,
    profilePic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'c1',
    title: 'Solar Water Pumps for Rural Schools',
    story: 'A community-led project to bring safe water access to rural schools through solar-powered pumps.',
    category: 'Community',
    fundingGoal: 12000,
    minimumContribution: 50,
    raisedAmount: 8400,
    deadline: '2026-09-15',
    rewardInfo: 'Backers receive project updates and community appreciation certificates.',
    imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=900&q=80',
    creatorEmail: 'creator@zendafund.com',
    status: 'approved',
  },
  {
    id: 'c2',
    title: 'Open Source Learning Pods',
    story: 'Creating accessible learning spaces with digital devices and mentor support for young learners.',
    category: 'Education',
    fundingGoal: 9000,
    minimumContribution: 40,
    raisedAmount: 6200,
    deadline: '2026-10-01',
    rewardInfo: 'Supporters receive early access to learning resources and digital badges.',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    creatorEmail: 'creator@zendafund.com',
    status: 'approved',
  },
  {
    id: 'c3',
    title: 'Green Rooftop Garden Initiative',
    story: 'Turning apartment rooftops into urban gardens that improve food access and reduce heat.',
    category: 'Environment',
    fundingGoal: 15000,
    minimumContribution: 60,
    raisedAmount: 9800,
    deadline: '2026-11-20',
    rewardInfo: 'Supporters get seasonal harvest updates and garden workshops.',
    imageUrl: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80',
    creatorEmail: 'creator@zendafund.com',
    status: 'pending',
  },
];
